// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ViaitaliaAPI.Data;

#nullable disable

namespace ViaitaliaAPI.Migrations
{
    [DbContext(typeof(TravelDBContext))]
    [Migration("20250726101430_Add Foriegn Keys ForImages")]
    partial class AddForiegnKeysForImages
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ViaitaliaAPI.Models.AttractionPlace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AttractionId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("attraction_id");

                    b.Property<string>("AttractionName")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("attraction_name");

                    b.Property<int?>("AverageDuration")
                        .HasColumnType("int")
                        .HasColumnName("average_duration");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("city_id");

                    b.Property<string>("CityName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("city_name");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EntryFee")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("entry_fee");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("image_id");

                    b.Property<string>("IsUnesco")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("is_UNESCO");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float")
                        .HasColumnName("longitude");

                    b.Property<string>("NearbyTransport")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nearby_transport");

                    b.Property<string>("OfficialWebsite")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("official_website");

                    b.Property<string>("OpeningHours")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("opening_hours");

                    b.Property<int?>("PopularityRank")
                        .HasColumnType("int")
                        .HasColumnName("popularity_rank");

                    b.Property<string>("Tags")
                        .HasColumnType("text")
                        .HasColumnName("tags");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.Property<string>("WheelchairAccessible")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("wheelchair_accessible");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("ImageId")
                        .IsUnique()
                        .HasFilter("[image_id] IS NOT NULL");

                    b.ToTable("AttractionPlaces");
                });

            modelBuilder.Entity("ViaitaliaAPI.Models.Beach", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Accessibility")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("BeachName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Beach_Name");

                    b.Property<string>("BeachType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Beach_Type");

                    b.Property<string>("BestMonths")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Best_Months");

                    b.Property<string>("BlueFlag")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Blue_Flag");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("city_id");

                    b.Property<string>("CityName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("City_Name");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facilities")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("image_id");

                    b.Property<string>("KindOfBeach")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Kind_of_Beach");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("PopularityScore")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Popularity_Score");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tag")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("WaterBodyName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Water_Body_Name");

                    b.Property<string>("WaterBodyType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Water_Body_Type");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("ImageId")
                        .IsUnique()
                        .HasFilter("[image_id] IS NOT NULL");

                    b.ToTable("Beaches");
                });

            modelBuilder.Entity("ViaitaliaAPI.Models.City", b =>
                {
                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("city_id");

                    b.Property<double?>("AreaKm2")
                        .HasColumnType("float")
                        .HasColumnName("area_km2");

                    b.Property<string>("CityCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("city_code");

                    b.Property<string>("CityName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("city_name");

                    b.Property<string>("ClimateZone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("climate_zone");

                    b.Property<string>("Currency")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("EmergencyNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("emergency_number");

                    b.Property<string>("GovernanceType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("governance_type");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("image_id");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float")
                        .HasColumnName("latitude");

                    b.Property<string>("LocalFestivals")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("local_festivals");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float")
                        .HasColumnName("longitude");

                    b.Property<string>("MayorName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("mayor_name");

                    b.Property<string>("NearestAirportIata")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("nearest_airport_iata");

                    b.Property<string>("NearestAirportName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nearest_airport_name");

                    b.Property<string>("OfficialLanguage")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("official_language");

                    b.Property<string>("OfficialWebsite")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("official_website");

                    b.Property<int?>("Population")
                        .HasColumnType("int")
                        .HasColumnName("population");

                    b.Property<string>("ProvinceName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("province_name");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("region");

                    b.Property<string>("RegionCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("region_code");

                    b.Property<string>("Tags")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("tags");

                    b.Property<string>("Timezone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("timezone");

                    b.Property<string>("TransportationTags")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("transportation_tags");

                    b.Property<string>("UnescoSites")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UNESCO_sites");

                    b.Property<string>("YearFounded")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("year_founded");

                    b.HasKey("CityId");

                    b.HasIndex("ImageId")
                        .IsUnique()
                        .HasFilter("[image_id] IS NOT NULL");

                    b.HasIndex(new[] { "CityName" }, "UQ_Cities_city_name")
                        .IsUnique()
                        .HasFilter("[city_name] IS NOT NULL");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("ViaitaliaAPI.Models.Hotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("address");

                    b.Property<string>("Amenities")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("amenities");

                    b.Property<string>("Budget")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("budget");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("city_id");

                    b.Property<string>("CityName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("city_name");

                    b.Property<string>("HotelName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("hotel_name");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("image_id");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float")
                        .HasColumnName("longitude");

                    b.Property<string>("OpeningHours")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("opening_hours");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phone_number");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("postal_code");

                    b.Property<int?>("Stars")
                        .HasColumnType("int")
                        .HasColumnName("stars");

                    b.Property<string>("Website")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("website");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("ImageId")
                        .IsUnique()
                        .HasFilter("[image_id] IS NOT NULL");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("ViaitaliaAPI.Models.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSizeInBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("ViaitaliaAPI.Models.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("city_id");

                    b.Property<string>("CityName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("city_name");

                    b.Property<string>("ClosingTime")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CuisineType")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("image_id");

                    b.Property<string>("OpeningTime")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PublicTransport")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RestaurantName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("ImageId")
                        .IsUnique()
                        .HasFilter("[image_id] IS NOT NULL");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("ViaitaliaAPI.Models.ShoppingMall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Affordability")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("affordability");

                    b.Property<int?>("AreaSqFt")
                        .HasColumnType("int")
                        .HasColumnName("area_sq_ft");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("city_id");

                    b.Property<string>("CityName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("city_name");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("description");

                    b.Property<string>("Facilities")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("facilities");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("image_id");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("location");

                    b.Property<string>("MallName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("mall_name");

                    b.Property<string>("OpeningHours")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("opening_hours");

                    b.Property<string>("ParkingCapacity")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("parking_capacity");

                    b.Property<string>("PopularBrands")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("popular_brands");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(3,1)")
                        .HasColumnName("rating");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("region");

                    b.Property<string>("TotalShops")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("total_shops");

                    b.Property<int?>("YearEstablished")
                        .HasColumnType("int")
                        .HasColumnName("year_established");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("ImageId")
                        .IsUnique()
                        .HasFilter("[image_id] IS NOT NULL");

                    b.ToTable("ShoppingMalls");
                });

            modelBuilder.Entity("ViaitaliaAPI.Models.AttractionPlace", b =>
                {
                    b.HasOne("ViaitaliaAPI.Models.City", "City")
                        .WithMany("AttractionPlaces")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_AttractionPlaces_Cities");

                    b.HasOne("ViaitaliaAPI.Models.Image", "Image")
                        .WithOne()
                        .HasForeignKey("ViaitaliaAPI.Models.AttractionPlace", "ImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("City");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("ViaitaliaAPI.Models.Beach", b =>
                {
                    b.HasOne("ViaitaliaAPI.Models.City", "City")
                        .WithMany("Beaches")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_Beaches_Cities");

                    b.HasOne("ViaitaliaAPI.Models.Image", "Image")
                        .WithOne()
                        .HasForeignKey("ViaitaliaAPI.Models.Beach", "ImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("City");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("ViaitaliaAPI.Models.City", b =>
                {
                    b.HasOne("ViaitaliaAPI.Models.Image", "Image")
                        .WithOne()
                        .HasForeignKey("ViaitaliaAPI.Models.City", "ImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Image");
                });

            modelBuilder.Entity("ViaitaliaAPI.Models.Hotel", b =>
                {
                    b.HasOne("ViaitaliaAPI.Models.City", "City")
                        .WithMany("Hotels")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_Hotels_Cities");

                    b.HasOne("ViaitaliaAPI.Models.Image", "Image")
                        .WithOne()
                        .HasForeignKey("ViaitaliaAPI.Models.Hotel", "ImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("City");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("ViaitaliaAPI.Models.Restaurant", b =>
                {
                    b.HasOne("ViaitaliaAPI.Models.City", "City")
                        .WithMany("Restaurants")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_Restaurants_Cities");

                    b.HasOne("ViaitaliaAPI.Models.Image", "Image")
                        .WithOne()
                        .HasForeignKey("ViaitaliaAPI.Models.Restaurant", "ImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("City");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("ViaitaliaAPI.Models.ShoppingMall", b =>
                {
                    b.HasOne("ViaitaliaAPI.Models.City", "City")
                        .WithMany("ShoppingMalls")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_ShoppingMalls_Cities");

                    b.HasOne("ViaitaliaAPI.Models.Image", "Image")
                        .WithOne()
                        .HasForeignKey("ViaitaliaAPI.Models.ShoppingMall", "ImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("City");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("ViaitaliaAPI.Models.City", b =>
                {
                    b.Navigation("AttractionPlaces");

                    b.Navigation("Beaches");

                    b.Navigation("Hotels");

                    b.Navigation("Restaurants");

                    b.Navigation("ShoppingMalls");
                });
#pragma warning restore 612, 618
        }
    }
}
